name: ECS Wait
description: Waits for target ECS services to stabilise
author: Rob Steel

inputs:
  aws-region:
    description: "The AWS region where the ECS cluster is located"
    required: true
  ecs-cluster:
    description: "The name of the ECS cluster"
    required: true
  ecs-services:
    description: "A JSON array of ECS services to monitor for stability"
    required: true
  retries:
    description: "The number of retries before timing out"
    required: true
    default: "5"
  verbose:
    description: "Enable verbose logging (true/false)"
    required: false
    default: "false"

outputs:
  retries:
    description: "The number of attempts made before services stabilised."

runs:
  using: "node20"
  main: "dist/index.js"